name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '3.1', '3.2', '3.3', 'ruby-head' ]
        activerecord: [ '7.1', '7.2', '8.0' ]
        exclude:
          # rails >= 8 requires ruby >= 3.2
          - ruby: '3.1'
            activerecord: '8.0'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Update RubyGems for Ruby 2
        run: |
          gem install rubygems-update -v '< 3.5' && update_rubygems
        if: matrix.ruby < '3.0'
      - name: Update RubyGems for Ruby 3
        run: |
          gem update --system
        if: matrix.ruby >= '3.0'
      - name: Install dependencies
        run: |
          BUNDLE_GEMFILE=./gemfiles/activerecord_${{matrix.activerecord}}.gemfile bundle install --jobs 4
      - name: Test with activerecord ${{matrix.activerecord}}
        run: BUNDLE_GEMFILE=./gemfiles/activerecord_${{matrix.activerecord}}.gemfile bundle exec rake
      - uses: codecov/codecov-action@v3
        if: matrix.ruby >= '3.3'
